/*INSERT INTO `EVENT` (`EVENT_ID`,`EVENT_ORGANIZER`,`SINGLE_EVENT`,`EVENT_END', 'EVENT_LOCATION',`EVENT_TYPE`,`EVENT_START`,
    'EVENT_START_TIME', 'EVENT_TITLE', 'DISPLAY_START_TIME')

VALUES (1,"Lucian","Y","PARTY", DATE,DATETIME,TIME, "TO BE OR NOT TO BE", "DATE");
